/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * Auto-generated API docs
 * OpenAPI spec version: 1.0
 */
import type { BranchDtoType } from './branchDtoType';
import type { OwnerDto } from './ownerDto';

export interface BranchDto {
  id: string;
  name: string;
  location: string;
  type: BranchDtoType;
  ownerId: string;
  owner: OwnerDto;
}
