/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * Auto-generated API docs
 * OpenAPI spec version: 1.0
 */

export type BranchDtoType = typeof BranchDtoType[keyof typeof BranchDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BranchDtoType = {
  OFFICE: 'OFFICE',
  MARKET: 'MARKET',
  WAREHOUSE: 'WAREHOUSE',
} as const;
