/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * Auto-generated API docs
 * OpenAPI spec version: 1.0
 */

export type CreateBranchDtoType = typeof CreateBranchDtoType[keyof typeof CreateBranchDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateBranchDtoType = {
  OFFICE: 'OFFICE',
  MARKET: 'MARKET',
  WAREHOUSE: 'WAREHOUSE',
} as const;
