/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * Auto-generated API docs
 * OpenAPI spec version: 1.0
 */
import type { CreateBranchDtoType } from './createBranchDtoType';

export interface CreateBranchDto {
  name: string;
  location: string;
  type: CreateBranchDtoType;
  ownerId: string;
}
