/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * Auto-generated API docs
 * OpenAPI spec version: 1.0
 */
import type { BranchDto } from './branchDto';
import type { UserDto } from './userDto';

export interface EmployeeDto {
  id: string;
  name: string;
  phoneNumber: string;
  email: string;
  branchId: string;
  userId: string;
  branch: BranchDto;
  user: UserDto;
}
