/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * Auto-generated API docs
 * OpenAPI spec version: 1.0
 */
import type { UserDto } from './userDto';

export interface OwnerDto {
  id: string;
  name: string;
  users?: UserDto[];
}
