/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * Auto-generated API docs
 * OpenAPI spec version: 1.0
 */

export interface UserDto {
  id: string;
  email: string;
  name?: string;
  createdAt: string;
  deletedAt: string;
}
